### ISSUE TITLE
Feature Request - Create Image if it does not exists in ECR

### ISSUE THREAD

**Issue by vikas027** [concourse/docker-image-resource#197]
At the moment build fails with below error if a repository does not exists on ECR

```
name unknown: The repository with name '<repo_name>' does not exist in the registry with id '<aws_account_id>'
```
It would be good to create the image automatically if it does not exists.

**Comment by hibbert** [comment]
I need this to so decided to do a PR - https://github.com/concourse/docker-image-resource/pull/199

**Comment by vito** [comment]
Is this a difference between ECR and other registries? I don't recall having to create a repository on Docker Hub for example.

**Comment by ghostsquad** [comment]
@vikas027 I disagree with this. I think making a repository and pushing an image should be entirely different operations, with repository creation happening _outside_ a concourse pipeline.

@vito In dockerhub, you do have to create each repository before you can push images to them, but that's a 1-time operation.

**Comment by vikas027** [comment]
> I think making a repository and pushing an image should be entirely different operations, with repository creation happening outside a concourse pipeline.

@ghostsquad I too disgree with creation happening outside a pipeline, maybe you can make it optional?

> In dockerhub, you do have to create each repository before you can push images to them

This is not true, pls see these logs. Here, repo `xxxx` never existed and was created automatically on [dockerhub](https://hub.docker.com/r/vikas027/xxxx/).
```bash
# docker tag 3fd9065eaf02 vikas027/xxxx
# docker push vikas027/xxxx
The push refers to a repository [docker.io/vikas027/xxxx]
cd7100a72410: Mounted from library/alpine
latest: digest: sha256:8c03bb07a531c53ad7d0f6e7041b64d81f99c6e493cb39abba56d956b40eacbc size: 528
#
```

**Comment by ghostsquad** [comment]
@vikas027 holy crap, I didn't know you could just arbitrarily push and have it create a new repo. That's both awesome and a little scary (but not a lot scary).

Anyways, I'm going to 🙇 bow out of this conversation with just one request. If you implement this, make the repo creation optional and default to `false` please. THOUGH on a side note, I think someone said this somewhere else, this particular resource is getting complicated by having to support so many backends. It would probably be beneficial to have a docker-ecr resource in order to reduce complexity. I have found that hosting a private registry internally (backed by S3) is much simpler overall than ECR.

**Comment by vikas027** [comment]
> I have found that hosting a private registry internally (backed by S3) is much simpler overall than ECR, though.

Yeah, I like the idea and was doing something similar a few months ago. The only reason to go with ECR was to manage permissions (thru policies) as my ECR repos are shared with hundreds of accounts. Also, it was easy to please security team as it was a native AWS solution :)

**Comment by xtremerui** [comment]
Closing. Please refer to https://github.com/concourse/docker-image-resource/pull/199#issuecomment-404546002.
