### ISSUE TITLE
Trigger on new docker tag

### ISSUE THREAD

**Issue by sammy** [concourse/docker-image-resource#217]
Hi all,

We currently use concourse to trigger deployments to our environments. It would be great if the docker-image resource could monitor the registry for new tags and trigger when one is present.

I know currently one can monitor one specific tag (eg latest) , but it would be much better if we could monitor for any new tag, or filter by regexp, similar to what the git resource does with tags

**Comment by sweeneyb** [comment]
Are you gating your promotions through environments at all?  I'm also trying to promote through stages, but we have some places requiring manual actions (ie, we still want a human to do an action and watch the deployment happen).

I've thought about watching for a specific tag to move and triggering on that. But right now, it's hard to do that and keep track of the version.  We could enforce a version label on the docker image, but that seems like I'm not addressing the core problem.

What I have now is a pipeline that, as it's final step, dynamically creates another pipeline with very specific tags in the resource.  As long as the dynamically generated pipeline name doesn't change, you maintain the history in concourse.  While it works, it doesn't feel great.

I'm thinking it would be useful to have a docker repo resource that watches for new images/tags.  The get itself would take in tag as a parameter (maybe as a file, so the output of the semver resource could be used?).  I think that would address #252 (and maybe #255 if the build were restructured a bit).  Would such a resource work for you?  I'd also be curious if @vito would weigh in, as I think he's had some thoughts on spinning off more specific resources in the past.

**Comment by vito** [comment]
Tags are tricky because they're not really something you can compare to each other for ordering, version-wise.

With concourse/rfcs#1 we'll be introducing 'spaces' which allow resources to detect multiple version streams, rather than one. The current plan is to have the `registry-image` detect each tag as a space. We plan to deprecate `docker-image` resource so we won't be updating it to be space-aware.

With that, you could have jobs trigger on each tag, or a filter of the tag names, and run continuously against each one.

**Comment by xtremerui** [comment]
With the above comment I would redirect the discussion to https://github.com/concourse/registry-image-resource/issues/77 and close this one.
