### ISSUE TITLE
Proposal: Option to not push to registry on `out`

### ISSUE THREAD

**Issue by akshaymankar** [concourse/docker-image-resource#249]
Currently the resource always pushes to a registry on `out`, but we have a usecase where we don't really want to push the image anywhere, but package it in a bosh release. So, I would like to propose a flag called `push_to_registry` which will default to true, but can be toggled off.

/cc @vlad-stoian

**Comment by jonahgeorge** [comment]
Has anyone come up with a temporary solution for this?

**Comment by vito** [comment]
There's not really any way to avoid pushing to the registry, since this resource is fundamentally about representing *external* state (as all resources are). The new pattern going forward is to use the [`builder` task](https://github.com/concourse/builder) instead for image building and then the [`registry-image` resource](https://github.com/concourse/registry-image-resource) for image pushing.

These aren't quite official yet, since I'd like to wrap up concourse/rfcs#7 before 'blessing' the `builder` task, but we're using them in production and it's going pretty well.

Gonna close this issue out though since there won't be any changes made to the `docker-image` resource to support this, especially as we'll be deprecating it in favor of `builder` and `registry-image`. Thanks all!
