### ISSUE TITLE
What happened to server_args?

### ISSUE THREAD

**Issue by dpgeekzero** [concourse/docker-image-resource#30]
The network range for the servers where I'm looking to run concourse fall in the magic 172.17.0.0/16 range, so I need to specify the '--bip' option to the docker daemon on startup or my build scripts can't access any of my other servers.

I see in #6 this was added, but then disappeared without any mention that I can find.

Adding docker daemon commands specific to my infrastructure to the build seems a little strange, but without I can't get this working at all.

**Comment by vito** [comment]
We removed it because it made certain configurations (e.g. insecure registries) impossible to deal with in more abstract ways. For example, `check` needs to know the insecure registries, but isn't using the Docker CLI. Previously the only way to configure them was via `server_args`, which meant either write an option parser (ugh) or promote the property into an actual schema.

So that kind of "wildcard" property is pretty dangerous. It sounds like we should just add another property to support your case.

**Comment by dpgeekzero** [comment]
@vito Agreed, that looked like a bit of a hack.

A specific property to address the docker bridge IP would be excellent!

**Comment by dpgeekzero** [comment]
@vito Makes sense.  A specific bridge_ip property would be great.

**Comment by vito** [comment]
Closing this since the original question was answered.
