### ISSUE TITLE
Caching is broken with docker 1.10

### ISSUE THREAD

**Issue by mariash** [concourse/docker-image-resource#46]
By ellerycrane in slack:

Because of the changes in docker 10, the only way to preserve the build cache is to use `docker save` of the image ​*from the place it was built*​, and then use `docker load` on the output of the former when building it again elsewhere.
the `docker-image-resource` does the `docker build` step in the `/out` script,
and has an option to use `save=true` in the `/in` script
However, in the context of `/in`, it will do a fresh `docker pull` which will not contain the build cache we want to preserve. So instead, I'd like to take the image built as part of the `/out` script and use it to update the latest version of the resource, rather than doing `/in`

See more: https://github.com/docker/docker/issues/20316

**Comment by ellerycrane** [comment]
To summarize the issue: 

With Docker 1.10, they made it so that pulling an image no longer pulls down the build cache for that image. This means that the only way to make use of Docker image layer caching, for both improved build times and reduced i/o time when pulling/pushing, is to make all subsequent builds of an image happen on the same system that did previous builds.

This is a problem for Concourse because no preservation of state happens between builds, so the build cache is lost. Pulling the image no longer retrieves the build cache, so every build must completely rebuild every layer in the docker image and push them all to the remote registry. (Incidentally, this also means that the `cache:true` parameter no longer works; it will pull down the latest image, but it won't contribute anything to the build except additional download time).

[This blog post](http://blog.runnable.com/post/145362675491/distributing-docker-cache-across-hosts) describes the underlying Docker issues in detail, and offers a potential work around: In Docker 1.11, they made it so that you can export the build cache by using `docker save <IMAGE> $(docker history -q <IMAGE>) > image.tar` and then loading that image before a build by using `docker load < image.tar`. The existing `docker-image-resource` code already largely supports this type of mechanism, and could be tweaked to work around the problem.

The biggest challenge I see is how to take the outputs from `/out`, where the image is built and `docker save` could be used to preserve the build cache, and funnel them into the same location as the outputs from `/in`.  

The current workflow (as I understand it) for building and pushing an image involves making a job with a `put` for the `docker-image-resource`, which will trigger `/out` to build and push the new resource to the remote repository, and then call `/in` to `docker pull` the new version of the resource from the remote repository. Not only does this add (potentially substantial) download times to the job as it needs to pull down the docker image it just built, but the build cache is lost as well. Could we change the workflow so that `/in` is not always called to fetch the new resource after a build, but instead make `/out` save the image and build history and update the resource's latest version to reference them?  

* [Docker Github issue about pulling build cache changes](https://github.com/docker/docker/issues/20316)
* [Blog post summarizing issue and possible workarounds](http://blog.runnable.com/post/145362675491/distributing-docker-cache-across-hosts)

**Comment by vito** [comment]
Should be fixed by https://github.com/concourse/docker-image-resource/pull/62
